services:
  proviant:
    build: .
    container_name: proviant
    restart: unless-stopped
    ports:
      - "8099:8000"
    volumes:
      - ./appdata:/data
    environment:
      - DATA_DIR=/data
      - SHOPPING_WEBHOOK_URL=https://n8n.dinsten.se/webhook/ica-shopping-list
      - SHOPPING_WEBHOOK_KEY=c25SxrKL6CIDsZHQLPuDA4S17n9IILMiCYGBTgElFXU

