services:
  proviant:
    build: .
    container_name: proviant
    restart: unless-stopped
    ports:
      - "8099:8000"
    volumes:
      - ./appdata:/data
    environment:
      - DATA_DIR=/data
      - SHOPPING_WEBHOOK_URL=${SHOPPING_WEBHOOK_URL}
      - SHOPPING_WEBHOOK_KEY=${SHOPPING_WEBHOOK_KEY}

